# Generated by Django 3.0.5 on 2021-01-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
