# Generated by Django 3.0.5 on 2021-01-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0002_auto_20210119_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist',
            new_name='songs',
        ),
    ]
